/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DeletedRouteImport } from './routes/deleted'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsBatchRdapRouteImport } from './routes/tools.batch-rdap'
import { Route as ApiPublicJobsJobIdDownloadRouteImport } from './routes/api/public/jobs/$jobId/download'

const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletedRoute = DeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBatchRdapRoute = ToolsBatchRdapRouteImport.update({
  id: '/tools/batch-rdap',
  path: '/tools/batch-rdap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsJobIdDownloadRoute =
  ApiPublicJobsJobIdDownloadRouteImport.update({
    id: '/api/public/jobs/$jobId/download',
    path: '/api/public/jobs/$jobId/download',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/deleted': typeof DeletedRoute
  '/discover': typeof DiscoverRoute
  '/pending': typeof PendingRoute
  '/tools/batch-rdap': typeof ToolsBatchRdapRoute
  '/api/public/jobs/$jobId/download': typeof ApiPublicJobsJobIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/deleted': typeof DeletedRoute
  '/discover': typeof DiscoverRoute
  '/pending': typeof PendingRoute
  '/tools/batch-rdap': typeof ToolsBatchRdapRoute
  '/api/public/jobs/$jobId/download': typeof ApiPublicJobsJobIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/deleted': typeof DeletedRoute
  '/discover': typeof DiscoverRoute
  '/pending': typeof PendingRoute
  '/tools/batch-rdap': typeof ToolsBatchRdapRoute
  '/api/public/jobs/$jobId/download': typeof ApiPublicJobsJobIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auctions'
    | '/deleted'
    | '/discover'
    | '/pending'
    | '/tools/batch-rdap'
    | '/api/public/jobs/$jobId/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auctions'
    | '/deleted'
    | '/discover'
    | '/pending'
    | '/tools/batch-rdap'
    | '/api/public/jobs/$jobId/download'
  id:
    | '__root__'
    | '/'
    | '/auctions'
    | '/deleted'
    | '/discover'
    | '/pending'
    | '/tools/batch-rdap'
    | '/api/public/jobs/$jobId/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsRoute: typeof AuctionsRoute
  DeletedRoute: typeof DeletedRoute
  DiscoverRoute: typeof DiscoverRoute
  PendingRoute: typeof PendingRoute
  ToolsBatchRdapRoute: typeof ToolsBatchRdapRoute
  ApiPublicJobsJobIdDownloadRoute: typeof ApiPublicJobsJobIdDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deleted': {
      id: '/deleted'
      path: '/deleted'
      fullPath: '/deleted'
      preLoaderRoute: typeof DeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/batch-rdap': {
      id: '/tools/batch-rdap'
      path: '/tools/batch-rdap'
      fullPath: '/tools/batch-rdap'
      preLoaderRoute: typeof ToolsBatchRdapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/$jobId/download': {
      id: '/api/public/jobs/$jobId/download'
      path: '/api/public/jobs/$jobId/download'
      fullPath: '/api/public/jobs/$jobId/download'
      preLoaderRoute: typeof ApiPublicJobsJobIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsRoute: AuctionsRoute,
  DeletedRoute: DeletedRoute,
  DiscoverRoute: DiscoverRoute,
  PendingRoute: PendingRoute,
  ToolsBatchRdapRoute: ToolsBatchRdapRoute,
  ApiPublicJobsJobIdDownloadRoute: ApiPublicJobsJobIdDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
