import type { AIJob } from "../lib/api";
import { formatDateTime } from "../lib/format";

export function AIJobList({ jobs }: { jobs: AIJob[] }) {
  const completed = jobs.filter((job) => job.status === "succeeded" || job.status === "failed").length;
  const percent = jobs.length ? Math.round((completed / jobs.length) * 100) : 0;
  const pending = jobs.filter((job) => job.status === "queued" || job.status === "running" || job.status === "deferred").length;
  return <section className="card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-[14px] font-semibold">AI Job 队列</h2><span className="text-[11px] text-ink-faint">持久化 · 可恢复租约 · 指数重试 · 不限每日额度</span></div><span className="text-[12px] text-ink-muted">待处理 {pending} · 约 {pending * 900} tokens</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-neutral/12"><div className="h-full rounded-full bg-accent transition-[width]" style={{ width: `${percent}%` }} /></div><p className="mt-1 text-[11px] text-ink-faint">当前列表完成进度 {percent}%；token 为按每任务 900 上限估算，实际以提供商返回为准。</p>{jobs.length === 0 ? <p className="mt-3 text-[12px] text-ink-faint">暂无任务</p> : <div className="table-scroll mt-3"><table className="w-full min-w-[560px] text-left text-[12px]"><thead className="border-b border-line text-ink-muted"><tr><th className="px-2 py-2 font-medium">域名</th><th className="px-2 py-2 font-medium">状态</th><th className="px-2 py-2 font-medium">尝试</th><th className="px-2 py-2 font-medium">创建</th><th className="px-2 py-2 font-medium">错误</th></tr></thead><tbody className="divide-y divide-line">{jobs.map((job) => <tr key={job.id}><td className="mono px-2 py-2">{job.domain}</td><td className="px-2 py-2">{job.status}</td><td className="tabular px-2 py-2">{job.attempts}/{job.max_attempts}</td><td className="px-2 py-2 text-ink-muted">{formatDateTime(job.created_at)}</td><td className="max-w-[240px] truncate px-2 py-2 text-ink-muted" title={job.last_error}>{job.last_error || "—"}</td></tr>)}</tbody></table></div>}</section>;
}
