/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    opacity: {
      0: "0",
      5: "0.05",
      8: "0.08",
      10: "0.1",
      12: "0.12",
      20: "0.2",
      25: "0.25",
      30: "0.3",
      40: "0.4",
      45: "0.45",
      50: "0.5",
      60: "0.6",
      75: "0.75",
      100: "1",
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)"],
        display: ["var(--font-roobert)"],
        mono: ["var(--font-mono)", "JetBrains Mono", "IBM Plex Mono", "ui-monospace", "monospace"],
      },
      colors: {
        "stone-canvas": "rgb(var(--stone-canvas) / <alpha-value>)",
        "pure-white": "rgb(var(--pure-white) / <alpha-value>)",
        "stone-border": "rgb(var(--stone-border) / <alpha-value>)",
        "stone-muted": "rgb(var(--stone-muted) / <alpha-value>)",
        "ash-gray": "rgb(var(--ash-gray) / <alpha-value>)",
        "warm-gray": "rgb(var(--warm-gray) / <alpha-value>)",
        "ink-black": "rgb(var(--ink-black) / <alpha-value>)",
        soot: "rgb(var(--soot) / <alpha-value>)",
        "sky-wash": "rgb(var(--sky-wash) / <alpha-value>)",
        "cyan-signal": "rgb(var(--cyan-signal) / <alpha-value>)",
        "cyan-edge": "rgb(var(--cyan-edge) / <alpha-value>)",
        parchment: "rgb(var(--parchment) / <alpha-value>)",
        "lake-blue": "rgb(var(--lake-blue) / <alpha-value>)",
        "periwinkle-mist": "rgb(var(--periwinkle-mist) / <alpha-value>)",
        "off-black": "rgb(var(--off-black) / <alpha-value>)",
        graphite: "rgb(var(--graphite) / <alpha-value>)",
        smoke: "rgb(var(--smoke) / <alpha-value>)",
        ash: "rgb(var(--ash) / <alpha-value>)",
        surface: {
          DEFAULT: "rgb(var(--surface) / <alpha-value>)",
          subtle: "rgb(var(--surface-subtle) / <alpha-value>)",
          muted: "rgb(var(--surface-muted) / <alpha-value>)",
          raised: "rgb(var(--surface-raised) / <alpha-value>)",
        },
        canvas: "rgb(var(--canvas) / <alpha-value>)",
        sidebar: "rgb(var(--sidebar) / <alpha-value>)",
        line: "rgb(var(--line) / <alpha-value>)",
        ink: {
          DEFAULT: "rgb(var(--ink) / <alpha-value>)",
          muted: "rgb(var(--ink-muted) / <alpha-value>)",
          faint: "rgb(var(--ink-faint) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "rgb(var(--accent) / <alpha-value>)",
          soft: "rgb(var(--accent-soft) / <alpha-value>)",
        },
        paper: "rgb(var(--paper) / <alpha-value>)",
        "card-mint": "rgb(var(--card-mint) / <alpha-value>)",
        blush: "rgb(var(--blush) / <alpha-value>)",
        "sea-foam": "rgb(var(--sea-foam) / <alpha-value>)",
        "mint-mist": "rgb(var(--mint-mist) / <alpha-value>)",
        "deep-teal": "rgb(var(--deep-teal) / <alpha-value>)",
        pine: "rgb(var(--pine) / <alpha-value>)",
        sage: "rgb(var(--sage) / <alpha-value>)",
        lake: "rgb(var(--lake) / <alpha-value>)",
        forest: "rgb(var(--forest) / <alpha-value>)",
        navy: "rgb(var(--navy) / <alpha-value>)",
        rose: "rgb(var(--rose) / <alpha-value>)",
        charcoal: "rgb(var(--charcoal) / <alpha-value>)",
        "illustration-ink": "rgb(var(--illustration-ink) / <alpha-value>)",
        review: "oklch(var(--review) / <alpha-value>)",
        danger: "oklch(var(--danger) / <alpha-value>)",
        success: "oklch(var(--success) / <alpha-value>)",
        warning: "oklch(var(--warning) / <alpha-value>)",
        info: "oklch(var(--info) / <alpha-value>)",
        neutral: "oklch(var(--neutral) / <alpha-value>)",
        "on-accent": "oklch(var(--on-accent) / <alpha-value>)",
        overlay: "oklch(var(--overlay) / <alpha-value>)",
      },
      // 规范：卡片与按钮 14px，徽章/标签全圆，导航项 7px。
      borderRadius: {
        card: "14px",
        button: "14px",
        pill: "999px",
        nav: "7px",
        tag: "999px",
      },
      boxShadow: {
        // 这套系统靠色块分层，不靠投影。保留键名让残留类名不至于报错。
        sm: "none",
        DEFAULT: "none",
        md: "none",
        lg: "none",
        xl: "none",
      },
      maxWidth: {
        workbench: "1200px",
      },
      spacing: {
        18: "4.5rem",
        22: "5.5rem",
      },
    },
  },
  plugins: [],
};
