/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "var(--font-abc-diatype-mono)",
          "JetBrains Mono",
          "IBM Plex Mono",
          "SFMono-Regular",
          "Menlo",
          "Consolas",
          "monospace",
        ],
        display: ["var(--font-untitled-serif)", "Georgia", "serif"],
        mono: ["var(--font-abc-diatype-mono)", "JetBrains Mono", "IBM Plex Mono", "ui-monospace", "monospace"],
      },
      colors: {
        parchment: "rgb(var(--parchment) / <alpha-value>)",
        "lake-blue": "rgb(var(--lake-blue) / <alpha-value>)",
        "periwinkle-mist": "rgb(var(--periwinkle-mist) / <alpha-value>)",
        "off-black": "rgb(var(--off-black) / <alpha-value>)",
        graphite: "rgb(var(--graphite) / <alpha-value>)",
        smoke: "rgb(var(--smoke) / <alpha-value>)",
        ash: "rgb(var(--ash) / <alpha-value>)",
        surface: {
          DEFAULT: "rgb(var(--surface) / <alpha-value>)",
          subtle: "rgb(var(--surface-subtle) / <alpha-value>)",
          muted: "rgb(var(--surface-muted) / <alpha-value>)",
          raised: "rgb(var(--surface-raised) / <alpha-value>)",
        },
        canvas: "rgb(var(--canvas) / <alpha-value>)",
        line: "rgb(var(--line) / <alpha-value>)",
        ink: {
          DEFAULT: "rgb(var(--ink) / <alpha-value>)",
          muted: "rgb(var(--ink-muted) / <alpha-value>)",
          faint: "rgb(var(--ink-faint) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "rgb(var(--accent) / <alpha-value>)",
          soft: "rgb(var(--accent-soft) / <alpha-value>)",
        },
        paper: "rgb(var(--paper) / <alpha-value>)",
        "card-mint": "rgb(var(--card-mint) / <alpha-value>)",
        blush: "rgb(var(--blush) / <alpha-value>)",
        "sea-foam": "rgb(var(--sea-foam) / <alpha-value>)",
        "mint-mist": "rgb(var(--mint-mist) / <alpha-value>)",
        "deep-teal": "rgb(var(--deep-teal) / <alpha-value>)",
        pine: "rgb(var(--pine) / <alpha-value>)",
        sage: "rgb(var(--sage) / <alpha-value>)",
        lake: "rgb(var(--lake) / <alpha-value>)",
        forest: "rgb(var(--forest) / <alpha-value>)",
        navy: "rgb(var(--navy) / <alpha-value>)",
        rose: "rgb(var(--rose) / <alpha-value>)",
        charcoal: "rgb(var(--charcoal) / <alpha-value>)",
        "illustration-ink": "rgb(var(--illustration-ink) / <alpha-value>)",
        review: "rgb(var(--review) / <alpha-value>)",
        danger: "rgb(var(--danger) / <alpha-value>)",
      },
      borderRadius: {
        card: "40px",
        button: "100px",
        pill: "1000px",
        nav: "100px",
        tag: "100px",
      },
      maxWidth: {
        workbench: "1432px",
      },
      spacing: {
        18: "4.5rem",
        22: "5.5rem",
      },
    },
  },
  plugins: [],
};
